[tools]
"ubi:nextest-rs/nextest" = { version = "cargo-nextest-0.9.105", exe = "cargo-nextest" }
"ubi:rustsec/rustsec" = { version = "cargo-audit/v0.21.2", exe = "cargo-audit" }
"ubi:taiki-e/cargo-llvm-cov" = "latest"
ansible = "12.0.0"
helm = "3.19.0"
helmfile = "1.1.7"
kustomize = "5.7.1"
pre-commit = "4.3.0"
rust = { version = "stable", components = "llvm-tools" }
tfswitch = "1.7.0"
watchexec = "2.3.2"

[tasks.build]
run = "cargo build --release --locked"

[tasks.install-local]
run = "cargo install --path . --force"

[tasks.test]
run = "cargo clippy --all-targets --all-features -- -D warnings && cargo nextest run"

[tasks.coverage]
run = "cargo llvm-cov --all-features --workspace --open"
