# Nextest configuration file
# See https://nexte.st/book/configuration.html

[profile.ci]
# CI profile for running tests in GitHub Actions
# Use fewer retries and stricter settings
retries = 0
fail-fast = false

# Show test output for failures
failure-output = "immediate-final"
success-output = "never"

# Set reasonable timeout
slow-timeout = { period = "60s", terminate-after = 2 }
